Deploy to Azure

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,111 +5,91 @@ on:
     branches: ["main"]
   pull_request:
     branches: ["main"]
-  workflow_dispatch:  
+  workflow_dispatch:
+
 env:
-    REGISTRY: gchr.io
-    IMAGE_NAME: ${{github.repository}}
+  REGISTRY: gchr.io
+  IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-    test:
-        if: github.event_name != 'workflow_dispatch'
-        runs-on: ubuntu-latest
-        strategy:
-            matrix:
-                node-version: ['20.19.3']
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-          
-            - name: Setup Node.js ${{matrix.node-version}}
-              uses: actions/setup-node@v4
-            
-            - name: Install API Dependencies
-              working-directory: ./api
-              run: npm install
-            
-            - name: Run unit tests
-              working-directory: ./api
-              run: npm test
-    
-            - name: Install Frontend Dependencies
-              working-directory: ./frontend
-              run: npm install
+  test:
+    if: github.event_name != 'workflow_dispatch'
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        node-version: ['20.19.3']
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
-    build-and-push:
-        if: github.event_name != 'workflow_dispatch'
-        needs: test
-        runs-on: ubuntu-latest
-        
+      - name: Setup Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
 
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-          
-            - name: Login to Docker Hub Registry
-              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
-            
-            # - name: Login to Docker Registry v2
-            #   uses: docker/login-action@v3
-            #   with:
-            #     registry: ${{env.REGISTRY}}
-            #     username: ${{github.actor}}
-            #     password: ${{secrets.DOCKER_PASSWORD}}
+      - name: Install API Dependencies
+        working-directory: ./api
+        run: npm install
 
-            # - name: Extract metadata
-            #   id: meta
-            #   uses: docker/metadata-actions@v5
-            #   with: 
-            #     images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
-            #     tags: type=ref, event=branch
-            #           type=ref, event=pr
-            #           type=sha.prefix={{branch}}-
-            #           type=raw, value=latest, enable={{is_default_branch}}
+      - name: Run unit tests
+        working-directory: ./api
+        run: npm test
 
-            - name: API image build and push
-              run: |
-                docker build -t ${{secrets.DOCKER_USERNAME}}/time-app-api ./api
-                docker push ${{secrets.DOCKER_USERNAME}}/time-app-api
-            
-            - name: Front image build and push
-              run: |
-                docker build -t ${{secrets.DOCKER_USERNAME}}/time-app-front ./frontend
-                docker push ${{secrets.DOCKER_USERNAME}}/time-app-front
-            
-    deploy:
-        if: github.event_name == 'workflow_dispatch'
-        runs-on: ubuntu-latest
-        
+      - name: Install Frontend Dependencies
+        working-directory: ./frontend
+        run: npm install
 
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-            
-            - name: VPS Deploy
-              uses: appleboy/ssh-action@v1
-              with:
-                host: ${{secrets.AZURE_VM_HOST}}
-                username: ${{secrets.AZURE_VM_USERNAME}}
-                key: ${{secrets.AZURE_VM_SSH_KEY}}
-                port: 22
-                script: |
-                    cd/opt/time-app
-                    git pull origin main
-                    docker-compose pull
-                    docker-compose down
-                    docker-compose up -d
-                    docker image prune -f
-                    sleep 20
-                    if curl -f http://loclahost:3000 > /dev/null/ 2 > &1; then
-                        echo "Frontent is healthy"
-                    else 
-                        echo "Frontent health check failed"
-                        exit 1
-                    fi
-                    
-                    if curl -f http://loclahost:5000 > /dev/null/ 2 > &1; then
-                        echo "API is healthy"
-                    else 
-                        echo "API health check failed"
-                        exit 1
-                    fi
+  build-and-push:
+    if: github.event_name != 'workflow_dispatch'
+    needs: test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Login to Docker Hub Registry
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
+      - name: API image build and push
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/time-app-api ./api
+          docker push ${{ secrets.DOCKER_USERNAME }}/time-app-api
+
+      - name: Front image build and push
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/time-app-front ./frontend
+          docker push ${{ secrets.DOCKER_USERNAME }}/time-app-front
+
+  deploy:
+    if: github.event_name == 'workflow_dispatch'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: VPS Deploy
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.AZURE_VM_HOST }}
+          username: ${{ secrets.AZURE_VM_USERNAME }}
+          key: ${{ secrets.AZURE_VM_SSH_KEY }}
+          port: 22
+          script: |
+            cd /opt/time-app
+            git pull origin main
+            docker-compose pull
+            docker-compose down
+            docker-compose up -d
+            docker image prune -f
+            sleep 20
+            if curl -f http://localhost:3000 > /dev/null 2>&1; then
+              echo "Frontend is healthy"
+            else
+              echo "Frontend health check failed"
+              exit 1
+            fi
+
+            if curl -f http://localhost:5000 > /dev/null 2>&1; then
+              echo "API is healthy"
+            else
+              echo "API health check failed"
+              exit 1
+            fi
